- name: Unmount /home/.snapshots
  mount:
    path: /home/.snapshots
    state: unmounted

- name: Remove /home/.snapshots Folder
  file:
    path: /home/.snapshots
    state: absent

- name: Create snapper config
  command: snapper -c home create-config /home
  args:
    creates: /etc/snapper/configs/home

- name: Delete Snapshots Subvolume created by Snapper
  command: btrfs subvolume delete /home/.snapshots

- name: Recreate /home/.snapshots mount point
  file:
    path: /home/.snapshots
    state: directory
    mode: '0750'

- name: Remount Snapshot Subvolumen
  command: mount -a
