# Installiere die nötigen Packages für unterschiedliche LSPs
- name: Installiere LSPs
  become: true
  pacman:
    name:
      - lua-language-server
      - ansible-lint
      - ansible-language-server
      - bash-language-server
    state: present

- name: Installiere iwe via cargo
  community.general.cargo:
    name:
      - iwe
      - iwes
    state: present
