- hosts: local
  become: true

#  pre_tasks:
#    - name: Install packages
#      pacman:
#        name: "{{ item }}"
#        state: present
#      loop: "{{ lookup('file', '../pkglist.txt').splitlines() }}"
  
  roles:
    #- pacman
    #- grub
    #- snapper
    #- grub_btrfs
    #- yay
    - lsp
